name: dart
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  bagel_db: 
    path: /Users/dudi/Documents/Apps/bagel-db-libraries/bagel_db
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
